
spring:
  application:
    name: logisticsApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090
bot:
  username: https://t.me/botbotbtobtowbsrbortsbot
  token: 7329553420:AAE9CLPog_Ici_yn8r1i4V4SpmloJGpBAiw
admin:
  chat:
    id: 7882316826
size: 10